// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebRandomizer.Models;

namespace WebRandomizer.Migrations
{
    [DbContext(typeof(RandomizerContext))]
    partial class RandomizerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("WebRandomizer.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConnectionId");

                    b.Property<string>("Device");

                    b.Property<string>("Guid");

                    b.Property<string>("Name");

                    b.Property<int>("SessionId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebRandomizer.Models.Seed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameName");

                    b.Property<string>("Guid");

                    b.Property<int>("Players");

                    b.Property<string>("SeedNumber");

                    b.Property<string>("Spoiler");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Seeds");
                });

            modelBuilder.Entity("WebRandomizer.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Guid");

                    b.Property<int?>("SeedId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("SeedId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("WebRandomizer.Models.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Guid");

                    b.Property<string>("Logic");

                    b.Property<byte[]>("Patch");

                    b.Property<string>("Player");

                    b.Property<int>("SeedId");

                    b.HasKey("Id");

                    b.HasIndex("SeedId");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("WebRandomizer.Models.Client", b =>
                {
                    b.HasOne("WebRandomizer.Models.Session")
                        .WithMany("Clients")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebRandomizer.Models.Session", b =>
                {
                    b.HasOne("WebRandomizer.Models.Seed", "Seed")
                        .WithMany()
                        .HasForeignKey("SeedId");
                });

            modelBuilder.Entity("WebRandomizer.Models.World", b =>
                {
                    b.HasOne("WebRandomizer.Models.Seed")
                        .WithMany("Worlds")
                        .HasForeignKey("SeedId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
