export default {
    0x60: "Progressive Tunic",
    0x5F: "Progressive Shield",
    0x5E: "Progressive Sword",
    0x0B: "Bow",
    0x58: "Silver Arrows",
    0x0C: "Blue Boomerang",
    0x2A: "Red Boomerang",
    0x0A: "Hookshot",
    0x29: "Mushroom",
    0x0D: "Powder",
    0x07: "Firerod",
    0x08: "Icerod",
    0x0f: "Bombos",
    0x10: "Ether",
    0x11: "Quake",
    0x12: "Lamp",
    0x09: "Hammer",
    0x13: "Shovel",
    0x14: "Flute",
    0x21: "Bugnet",
    0x1D: "Book",
    0x16: "Bottle",
    0x15: "Somaria",
    0x18: "Byrna",
    0x19: "Cape",
    0x1A: "Mirror",
    0x4B: "Boots",
    0x61: "Progressive Glove",
    0x1E: "Flippers",
    0x1F: "Moon Pearl",
    0x4E: "Half Magic",
    0x17: "Heart Piece",
    0x3E: "Heart Container",
    0x3F: "Sanc Heart Container",
    0x28: "Three Bombs",
    0x43: "Arrow",
    0x44: "Ten Arrows",
    0x34: "One Rupee",
    0x35: "Five Rupees",
    0x36: "Twenty Rupees",
    0x47: "Twenty Rupees",
    0x41: "Fifty Rupees",
    0x40: "One Hundred Rupees",
    0x46: "Three Hundred Rupees",
    0x51: "5 Bombs Upgrade",
    0x52: "10 Bombs Upgrade",
    0x53: "5 Arrows Upgrade",
    0x54: "10 Arrow Upgrade",
    0xC2: "Missile",
    0xC3: "Super",
    0xC4: "Power Bomb",
    0xB0: "Grapple",
    0xB1: "X-Ray",
    0xC0: "Energy Tank",
    0xC1: "Reserve Tank",
    0xBB: "Charge",
    0xBC: "Ice",
    0xBD: "Wave",
    0xBE: "Spazer",
    0xBF: "Plasma",
    0xB2: "Varia",
    0xB6: "Gravity",
    0xB4: "Morph",
    0xB9: "Bombs",
    0xB3: "Spring Ball",
    0xB5: "Screw Attack",
    0xB7: "Hi-Jump Boots",
    0xB8: "Space Jump",
    0xBA: "Speed Booster",
    0x2B: "Bottle With Red Potion",
    0x2C: "Bottle With Green Potion",
    0x2D: "Bottle With Blue Potion",
    0x3D: "Bottle With Fairy",
    0x3C: "Bottle With Bee",
    0x48: "Bottle With Gold Bee",
    0x2E: "Red Content",
    0x2F: "Green Content",
    0x30: "Blue Content",
    0x0E: "Bee Content",
};