export const smz3ItemNames = {
    0x60: "Progressive Tunic",
    0x5F: "Progressive Shield",
    0x5E: "Progressive Sword",
    0x0B: "Bow",
    0x58: "Silver Arrows",
    0x0C: "Blue Boomerang",
    0x2A: "Red Boomerang",
    0x0A: "Hookshot",
    0x29: "Mushroom",
    0x0D: "Powder",
    0x07: "Firerod",
    0x08: "Icerod",
    0x0f: "Bombos",
    0x10: "Ether",
    0x11: "Quake",
    0x12: "Lamp",
    0x09: "Hammer",
    0x13: "Shovel",
    0x14: "Flute",
    0x21: "Bugnet",
    0x1D: "Book",
    0x16: "Bottle",
    0x15: "Somaria",
    0x18: "Byrna",
    0x19: "Cape",
    0x1A: "Mirror",
    0x4B: "Boots",
    0x61: "Progressive Glove",
    0x1E: "Flippers",
    0x1F: "Moon Pearl",
    0x4E: "Half Magic",
    0x17: "Heart Piece",
    0x3E: "Heart Container",
    0x3F: "Sanc Heart Container",
    0x28: "Three Bombs",
    0x43: "Arrow",
    0x44: "Ten Arrows",
    0x34: "One Rupee",
    0x35: "Five Rupees",
    0x36: "Twenty Rupees",
    0x47: "Twenty Rupees",
    0x41: "Fifty Rupees",
    0x40: "One Hundred Rupees",
    0x46: "Three Hundred Rupees",
    0x51: "5 Bombs Upgrade",
    0x52: "10 Bombs Upgrade",
    0x53: "5 Arrows Upgrade",
    0x54: "10 Arrow Upgrade",
    0xC2: "Missile",
    0xC3: "Super",
    0xC4: "Power Bomb",
    0xB0: "Grapple",
    0xB1: "X-Ray",
    0xC0: "Energy Tank",
    0xC1: "Reserve Tank",
    0xBB: "Charge",
    0xBC: "Ice",
    0xBD: "Wave",
    0xBE: "Spazer",
    0xBF: "Plasma",
    0xB2: "Varia",
    0xB6: "Gravity",
    0xB4: "Morph",
    0xB9: "Bombs",
    0xB3: "Spring Ball",
    0xB5: "Screw Attack",
    0xB7: "Hi-Jump Boots",
    0xB8: "Space Jump",
    0xBA: "Speed Booster",
    0x2B: "Bottle With Red Potion",
    0x2C: "Bottle With Green Potion",
    0x2D: "Bottle With Blue Potion",
    0x3D: "Bottle With Fairy",
    0x3C: "Bottle With Bee",
    0x48: "Bottle With Gold Bee",
    0x2E: "Red Content",
    0x2F: "Green Content",
    0x30: "Blue Content",
    0x0E: "Bee Content",
    0x7F: "Hyrule Castle Map",
    0x7D: "Eastern Palace Map",
    0x7C: "Desert Palace Map",
    0x75: "Tower of Hera Map",
    0x79: "Palace of Darkness Map",
    0x7A: "Swamp Palace Map",
    0x77: "Skull Woods Map",
    0x74: "Thieves Town Map",
    0x76: "Ice Palace Map",
    0x78: "Misery Mire Map",
    0x73: "Turtle Rock Map",
    0x72: "Ganons Tower Map",
 
    0x8D: "Eastern Palace Compass",
    0x8C: "Desert Palace Compass",
    0x85: "Tower of Hera Compass",
    0x89: "Palace of Darkness Compass",
    0x8A: "Swamp Palace Compass",
    0x87: "Skull Woods Compass",
    0x84: "Thieves Town Compass",
    0x86: "Ice Palace Compass",
    0x88: "Misery Mire Compass",
    0x83: "Turtle Rock Compass",
    0x82: "Ganons Tower Compass",
 
    0x9D: "Eastern Palace Big Key",
    0x9C: "Desert Palace Big Key",
    0x95: "Tower of Hera Big Key",
    0x99: "Palace of Darkness Big Key",
    0x9A: "Swamp Palace Big Key",
    0x97: "Skull Woods Big Key",
    0x94: "Thieves Town Big Key",
    0x96: "Ice Palace Big Key",
    0x98: "Misery Mire Big Key",
    0x93: "Turtle Rock Big Key",
    0x92: "Ganons Tower Big Key",
 
    0xA0: "Sewer Key",
    0xA4: "Castle Tower Key",
    0xA3: "Desert Palace Key",
    0xAA: "Tower of Hera Key",
    0xA6: "Palace of Darkness Key",
    0xA5: "Swamp Palace Key",
    0xA8: "Skull Woods Key",
    0xAB: "Thieves Town Key",
    0xA9: "Ice Palace Key",
    0xA7: "Misery Mire Key",
    0xAC: "Turtle Rock Key",
    0xAD: "Ganons Tower Key",
 
    0x24: "Small Key",
    0x25: "Compass",
    0x32: "Big Key",
    0x33: "Map",

    0xCA: "Brinstar Map",
    0xCB: "Wrecked Ship Map",
    0xCC: "Maridia Map",
    0xCD: "Lower Norfair Map",

    0xD0: "Crateria Level 1 Key",
    0xD1: "Crateria Level 2 Key",
    0xD2: "Crateria Boss Key",
    0xD3: "Brinstar Level 1 Key",
    0xD4: "Brinstar Level 2 Key",
    0xD5: "Brinstar Boss Key",
    0xD6: "Norfair Level 1 Key",
    0xD7: "Norfair Level 2 Key",
    0xD8: "Norfair Boss Key",
    0xD9: "Maridia Level 1 Key",
    0xDA: "Maridia Level 2 Key",
    0xDB: "Maridia Boss Key",
    0xDC: "Wrecked Ship Level 1 Key",
    0xDD: "Wrecked Ship Boss Key",
    0xDE: "Lower Norfair Level 1 Key",
    0xDF: "Lower Norfair Boss Key",
};

export const smItemNames = {
    0x00: "Energy Tank",
    0x01: "Missile",
    0x02: "Super Missile",
    0x03: "Power Bomb",
    0x04: "Bombs",
    0x05: "Charge",
    0x06: "Ice Beam",
    0x07: "Hi-Jump Boots",
    0x08: "Speed Booster",
    0x09: "Wave Beam",
    0x0A: "Spazer",
    0x0B: "Spring Ball",
    0x0C: "Varia Suit",
    0x0D: "Gravity Suit",
    0x0E: "X-ray Scope",
    0x0F: "Plasma Beam",
    0x10: "Grapple Beam",
    0x11: "Space Jump",
    0x12: "Screw Attack",
    0x13: "Morph Ball",
    0x14: "Reserve Tank",
    0x15: "Unused",
    0x16: "Unused",
    0x17: "Unused",
    0x18: "Unused",
    0x19: "Unused",
    0x1A: "Unused",
    0x1B: "Unused",
    0x1C: "Unused",
    0x1D: "Unused",
    0x1E: "Unused",
    0x1F: "Unused",
    0x20: "Crateria L1 Key",
    0x21: "Crateria L2 Key",
    0x22: "Crateria Boss Key",
    0x23: "Brinstar L1 Key",
    0x24: "Brinstar L2 Key",
    0x25: "Brinstar Boss Key",
    0x26: "Norfair L1 Key",
    0x27: "Norfair L2 Key",
    0x28: "Norfair Boss Key",
    0x29: "Maridia L1 Key",
    0x2A: "Maridia L2 Key",
    0x2B: "Maridia Boss Key",
    0x2C: "Wrecked Ship L1 Key",
    0x2D: "Wrecked Ship Boss Key",
    0x2E: "Lower Norfair L1 Key",
    0x2F: "Lower Norfair Boss Key",
};